# Generated by Django 3.2.4 on 2021-06-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_page', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=100, null=True)),
                ('googlemaps_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('main_title', models.CharField(max_length=100)),
                ('main_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='main/images')),
                ('gluten_free_logo', models.FileField(blank=True, null=True, upload_to='main/logos')),
                ('gluten_free_message', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vegan_logo', models.FileField(blank=True, null=True, upload_to='main/logos')),
                ('vegan_message', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('natural_logo', models.FileField(blank=True, null=True, upload_to='main/logos')),
                ('natural_message', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('organic_logo', models.FileField(blank=True, null=True, upload_to='main/logos')),
                ('organic_message', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('products_title', models.CharField(max_length=100)),
                ('products_description', models.TextField()),
                ('recipe_title', models.CharField(max_length=50)),
                ('recipe_description', models.TextField()),
                ('hours_oneline', models.CharField(max_length=100)),
                ('hours_weekdays_morning', models.CharField(blank=True, max_length=50, null=True)),
                ('hours_weekdays_evening', models.CharField(blank=True, max_length=50, null=True)),
                ('hours_weekends', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/images')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/images')),
                ('properties', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.maincategory')),
            ],
        ),
    ]
