# Generated by Django 3.2.4 on 2021-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
