# Generated by Django 3.2.4 on 2021-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_homeinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=models.ImageField(upload_to='static/main/images'),
        ),
    ]
