# Generated by Django 3.2.4 on 2021-06-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_homeinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('facebook_page', models.CharField(max_length=100)),
                ('instagram_page', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='main/images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='main/images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='homeinfo',
            old_name='title',
            new_name='hours_oneline',
        ),
        migrations.RenameField(
            model_name='homeinfo',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='gluten_free_logo',
            field=models.ImageField(default='-', upload_to='main/logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='hours_weekdays',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='hours_weekdays_evening',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='hours_weekdays_morning',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='main_description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='main_title',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='natural_logo',
            field=models.ImageField(default='-', upload_to='main/logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='organic_logo',
            field=models.ImageField(default='-', upload_to='main/logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='products_description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='products_title',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='recipe_description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='recipe_title',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='store_name',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='vegan_logo',
            field=models.ImageField(default='-', upload_to='main/logos'),
            preserve_default=False,
        ),
    ]
