# Generated by Django 3.2.4 on 2021-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_homeinfo_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='main_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='main_title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
