# Generated by Django 3.2.4 on 2021-06-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210615_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='main_image',
            field=models.ImageField(upload_to='main/images', verbose_name='main_image'),
        ),
    ]
