# Generated by Django 3.2.4 on 2021-06-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_homeinfo_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='gluten_free_logo',
            field=models.ImageField(upload_to='main/logos', verbose_name='gluten free image'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='main_image',
            field=models.ImageField(upload_to='main/images', verbose_name='image'),
        ),
    ]
