# Generated by Django 3.2.4 on 2021-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210615_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='store_name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
    ]
