# Generated by Django 3.2.4 on 2021-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_homeinfo_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_page',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_page',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='gluten_free_logo',
            field=models.ImageField(upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='main_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='main_image',
            field=models.ImageField(upload_to='main/images'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='main_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='store_name',
            field=models.CharField(max_length=50),
        ),
    ]
