# Generated by Django 3.2.4 on 2021-06-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210616_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
