# Generated by Django 3.2.4 on 2021-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210616_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
