# Generated by Django 3.2.4 on 2021-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contactinfo_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='googlemaps_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
