# Generated by Django 3.2.4 on 2021-06-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contactinfo_googlemaps_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='location',
            new_name='address',
        ),
    ]
