# Generated by Django 3.2.4 on 2021-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_location_contactinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategories',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
