# Generated by Django 3.2.4 on 2021-06-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210616_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategories',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
