# Generated by Django 3.2.4 on 2021-06-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210616_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeinfo',
            old_name='hours_weekdays',
            new_name='hours_weekends',
        ),
    ]
