# Generated by Django 3.2.4 on 2021-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210619_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='gluten_free_logo',
            field=models.ImageField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='hours_weekdays_evening',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='hours_weekdays_morning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='hours_weekends',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/images'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='natural_logo',
            field=models.ImageField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='organic_logo',
            field=models.ImageField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='vegan_logo',
            field=models.ImageField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/images'),
        ),
    ]
