# Generated by Django 3.2.4 on 2021-06-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210619_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
