# Generated by Django 3.2.4 on 2021-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210622_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='gluten_free_message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='natural_message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='organic_message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='vegan_message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='gluten_free_logo',
            field=models.FileField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='natural_logo',
            field=models.FileField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='organic_logo',
            field=models.FileField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='vegan_logo',
            field=models.FileField(blank=True, null=True, upload_to='main/logos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='main/images'),
        ),
    ]
